name: Mr.undisputed
favicon: null
layout_spectrum: 0.39777507493272424
typography_spectrum: 0.9946503525134176
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5437217184808105
  lightness: 0.4808891783468425
  saturation: 0.4292778878007084
  rhythmicContrast: 0.9697985583916306
purpose: []
